export const GET_EVENT_ID_REQUEST = 'GET_EVENT_ID_REQUEST';
export const GET_EVENT_ID_SUCCESS = 'GET_EVENT_ID_SUCCESS';
export const GET_EVENT_ID_ERROR = 'GET_EVENT_ID_ERROR';

export const GET_EVENT_DETAILS_REQUEST = 'GET_EVENT_DETAILS_REQUEST';
export const GET_EVENT_DETAILS_SUCCESS = 'GET_EVENT_DETAILS_SUCCESS';
export const GET_EVENT_DETAILS_ERROR = 'GET_EVENT_DETAILS_ERROR';
